from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    use_camera = LaunchConfiguration('use_camera')
    use_viewer = LaunchConfiguration('use_viewer')
    use_debug_view = LaunchConfiguration('use_debug_view')
    use_planning_tail = LaunchConfiguration('use_planning_tail')
    use_led = LaunchConfiguration('use_led')
    use_rviz = LaunchConfiguration('use_rviz')
    publish_map = LaunchConfiguration('publish_map')

    return LaunchDescription([
        DeclareLaunchArgument(
            'use_camera',
            default_value='true',
            description='Start camera_driver for /image_raw when true.',
        ),
        DeclareLaunchArgument(
            'use_viewer',
            default_value='false',
            description='Start viewer_node GUI when true.',
        ),
        DeclareLaunchArgument(
            'use_debug_view',
            default_value='true',
            description='Start lane_debug_view from detection_node when true.',
        ),
        DeclareLaunchArgument(
            'use_planning_tail',
            default_value='true',
            description='Start src-derived drive/behavior/A*/cmd_mux/safety tail.',
        ),
        DeclareLaunchArgument(
            'use_led',
            default_value='true',
            description='Start LED behavior and Arduino LED I/O nodes when true.',
        ),
        DeclareLaunchArgument(
            'use_rviz',
            default_value='true',
            description='Start RViz with scan, pose, TF, and left Hybrid A* reverse path displays.',
        ),
        DeclareLaunchArgument(
            'publish_map',
            default_value='true',
            description='Publish the experimental /map OccupancyGrid from localization_slam.',
        ),
        Node(
            package='lane_length_pkg',
            executable='camera_driver',
            name='camera_driver',
            output='screen',
            condition=IfCondition(use_camera),
        ),
        Node(
            package='lane_length_pkg',
            executable='detection_node',
            name='detection_node',
            output='screen',
            parameters=[{
                'use_camera_rectification': True,
                'publish_bev_image': True,
                'lane_roi_top_ratio': 0.58,
                'lane_roi_bottom_ratio': 0.90,
                'src_top_y_ratio': 0.60,
                'src_top_half_width_ratio': 0.26,
                'debug_view_bottom_crop_ratio': 0.10,
                'max_lane_miss': 10,
                'status_requires_current_detection': False,
                'bottom_visible_from_camera_m': 0.27,
                'lateral_zero_bias_m': 0.0,
                'forward_query_margin_m': 0.0,
                'steer_forward_m': 0.35,
                'stop_forward_m': 0.35,
                'heading_lookahead_m': 0.18,
                'max_forward_extrapolation_m': 0.0,
                'use_farthest_visible_width_for_stop': False,
                'right_line_left_offset_m': 0.10,
                'left_line_right_offset_m': 0.10,
                'show_debug_view': ParameterValue(use_debug_view, value_type=bool),
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='integration_node',
            name='integration_node',
            output='screen',
            parameters=[{
                'obstacle_direction': 'both',
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='led_signal',
            name='led_signal',
            output='screen',
            parameters=[{
                'image_topic': '/image_raw',
                'roi_left_ratio': 0.25,
                'roi_right_ratio': 0.75,
                'roi_top_ratio': 0.52,
                'roi_bottom_ratio': 1.00,
                'min_detect_bbox_area_px': 1200,
                'max_detect_bbox_area_px': 3000,
                'bbox_lock_confirm_sec': 1.0,
                'track_locked_strip': False,
                'freeze_locked_bbox': True,
                'wait_pass_redetect_interval_frames': 5,
                'wait_pass_redetect_miss_limit': 3,
                'enable_image_filter': True,
                'image_filter_v4l2_value_mode': True,
                'image_filter_brightness': -40.0,
                'image_filter_contrast': 32.0,
                'image_filter_saturation': 40.0,
                'image_filter_gain': 5.0,
                'dark_box_thresh': 70,
                'min_box_area': 10000,
                'led_thresh': 170,
                'min_led_area': 5,
                'max_led_area': 2500,
                'max_led_y_diff': 25,
                'slot_tol_pixels': 18,
                'show_debug_view': ParameterValue(use_debug_view, value_type=bool),
                'camera_info_yaml': PathJoinSubstitution([
                    FindPackageShare('lane_length_pkg'),
                    'config',
                    'fisheye.yaml',
                ]),
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='decision_node',
            name='decision_node',
            output='screen',
            parameters=[{
                'lane_status_topic': '/lane_status',
                'guidance_source_topic': '/lane_guidance_source',
                'robot_width_m': 0.19,
                'width_margin_m': 0.0,
                'width_hysteresis_m': 0.0,
                'min_valid_width_m': 0.05,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='control_node',
            name='control_node',
            output='screen',
            parameters=[{
                'center_error_m_topic': '/lane_error_center_m',
                'left_error_m_topic': '/lane_error_left_m',
                'right_error_m_topic': '/lane_error_right_m',
                'heading_error_topic': '/lane_heading_error',
                'lane_status_topic': '/lane_status',
                'cmd_vel_topic': '/cmd_vel_lane',
                'max_ang_z': 0.14,
                'kp_m': 0.45,
                'k_heading': 0.08,
                'steering_sign': -1.0,
                'nominal_speed': 0.070,
                'min_speed': 0.050,
                'slow_error_m': 0.08,
                'hard_stop_error_m': 0.15,
                'require_heading': False,
                'lane_timeout_sec': 0.50,
                'heading_timeout_sec': 0.35,
                'straight_pursuit_gain': 0.05,
                'straight_heading_gain': 0.05,
                'straight_boost_pursuit_gain': 0.22,
                'straight_boost_heading_gain': 0.22,
                'curve_pursuit_gain': 0.80,
                'curve_heading_gain': 1.10,
                'angle_max_step_deg': 6.0,
                'use_path_pursuit': False,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='localization_slam',
            name='localization_slam',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'localization_hz': 20.0,
                'map_publish_hz': 1.0,
                'map_frame': 'odom',
                'publish_map': ParameterValue(publish_map, value_type=bool),
                'map_resolution': 0.025,
                'map_width': 160,
                'map_height': 160,
                'map_origin_x': -2.0,
                'map_origin_y': -2.0,
                'clear_map_each_update': False,
                'scan_yaw_offset_deg': 180.0,
                'scan_ignore_angle_min_deg': -30.0,
                'scan_ignore_angle_max_deg': 30.0,
                'scan_ignore_all_ranges': True,
                'publish_map_odom_tf': False,
                'identity_map_odom_tf': False,
                'odom_topic': '/odom',
                'scan_topic': '/scan',
                'imu_topic': '/imu',
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='space_memory',
            name='space_memory',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'search_radius_m': 3.0,
                'narrow_threshold_m': 0.40,
                'pullover_min_width_m': 0.50,
                'use_map': False,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='scene_fusion_node',
            name='scene_fusion_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'use_pose_topic': True,
                'publish_pose': False,
                'pose_topic': '/pose',
                'opponent_topic': '/perception/opponent_vehicle',
                'min_valid_road_width_m': 0.05,
                'road_class_a_min_m': 0.47,
                'opponent_clear_sec': 3.0,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='deadlock',
            name='deadlock',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'detection_hz': 20.0,
                'deadlock_distance_m': 1.5,
                'near_threshold_m': 0.8,
                'facing_angle_threshold_rad': 0.52,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='cooperation',
            name='cooperation',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'decision_hz': 10.0,
                'max_negotiation_sec': 20.0,
                'timeout_default_yield': False,
                'protocol_prompt_delay_sec': 1.5,
                'decision_hold_sec': 2.0,
                'v2v_use_rps': True,
                'prompt_protocol_choice': True,
                'manual_rps_input': True,
                'default_rps_choice': 'ROCK',
                'v2v_advertise_sec': 0.8,
                'v2v_sign_timeout_sec': 1.0,
                'rps_countdown_sec': 0.0,
                'led_trigger_enabled': True,
                'led_trigger_mask': '11111',
                'led_trigger_min_bbox_area_px': 1200,
                'road_class_a_min_m': 0.47,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='led_behavior',
            name='led_behavior',
            output='screen',
            condition=IfCondition(use_led),
            parameters=[{
                'led_hz': 5.0,
                'min_hold_sec': 0.5,
                'v2v_pattern_timeout_sec': 1.0,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='led_io',
            name='led_io',
            output='screen',
            condition=IfCondition(use_led),
            parameters=[{
                'backend': 'arduino_serial',
                'arduino_port': '/dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_14238313834351212240-if00',
                'arduino_fallback_ports': ['/dev/ttyACM1', '/dev/ttyUSB1'],
                'arduino_blocked_ports': ['/dev/tb3_lidar'],
                'arduino_baudrate': 9600,
                'arduino_command_newline': True,
                'arduino_raw_mask_enabled': True,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='drive_mode_node',
            name='drive_mode_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'yield_accept_wait_sec': 3.0,
                'blocked_reverse_delay_sec': 3.0,
                'yield_wait_clear_sec': 5.0,
                'led_negotiation_mask': '11111',
                'led_negotiation_min_bbox_area_px': 1200,
                'led_negotiation_timeout_sec': 1.0,
                'led_negotiation_hold_sec': 3.0,
                'negotiation_hold_sec': 25.0,
                'right_offset_pass_min_sec': 1.5,
                'right_offset_pass_timeout_sec': 8.0,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='behavior_plan_node',
            name='behavior_plan_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'reverse_speed': 0.020,
                'yield_reverse_extra_back_m': 0.0,
                'yield_reverse_extra_lateral_m': 0.10,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='reverse_astar_planner_node',
            name='reverse_astar_planner_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'scan_topic': '/scan',
                'map_topic': '/map',
                'use_map_obstacles': True,
                'use_scan_obstacles': False,
                'map_occupied_threshold': 50,
                'map_collision_radius_m': 0.07,
                'map_unknown_is_obstacle': False,
                'scan_yaw_offset_deg': 180.0,
                'reverse_obstacle_avoidance': False,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='path_track_node',
            name='path_track_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'lookahead_distance_m': 0.15,
                'reverse_lookahead_distance_m': 0.22,
                'reverse_speed': 0.020,
                'max_angular_speed': 0.30,
                'reverse_max_angular_speed': 0.15,
                'goal_tolerance_m': 0.03,
                'scan_topic': '/scan',
                'scan_yaw_offset_deg': 180.0,
                'reverse_obstacle_guard': False,
                'reverse_obstacle_stop_m': 0.22,
                'reverse_obstacle_y_half_m': 0.18,
                'reverse_obstacle_min_points': 2,
                'scan_timeout_sec': 0.5,
            }],
        ),
        Node(
            package='lane_length_pkg',
            executable='cmd_mux_node',
            name='cmd_mux_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
        ),
        Node(
            package='lane_length_pkg',
            executable='safety_filter_node',
            name='safety_filter_node',
            output='screen',
            condition=IfCondition(use_planning_tail),
            parameters=[{
                'max_linear_accel': 0.06,
                'max_linear_speed': 0.08,
                'led_stop_topic': '/perception/opponent_v2v_sign',
                'led_stop_bbox_area_px': 1200,
                'led_stop_confirm_sec': 3.0,
                'led_stop_hold_sec': 0.5,
            }],
        ),
        Node(
            package='rviz2',
            executable='rviz2',
            name='rviz2',
            output='screen',
            condition=IfCondition(use_rviz),
            arguments=[
                '-d',
                PathJoinSubstitution([
                    FindPackageShare('lane_length_pkg'),
                    'rviz',
                    'lane_pipeline.rviz',
                ]),
            ],
        ),
        Node(
            package='lane_length_pkg',
            executable='viewer_node',
            name='viewer_node',
            output='screen',
            condition=IfCondition(use_viewer),
            parameters=[{
                'show_obstacles': True,
                'use_actual_bev_background': True,
                'lateral_zero_bias_m': 0.0,
            }],
        ),
    ])
